name: Build Docker Images for Jucity
on:
  workflow_dispatch:
    inputs:
      tag:
        description: "The tag version you want to build"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: 'juicity/juicity'
          ref: ${{ github.event.inputs.tag }}
          path: 'juicity'

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Setup QEMU for Docker Buildx
        uses: docker/setup-qemu-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker metadata
        id: metadata
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/litjourney/juicity
      - name: Get tag to build
        id: tag
        run: |
          echo "latest=ghcr.io/litjourney/juicity:latest" >> $GITHUB_OUTPUT
          if [[ -z "${{ github.event.inputs.tag }}" ]]; then
            echo "versioned=ghcr.io/litjourney/juicity:${{ github.ref_name }}" >> $GITHUB_OUTPUT
          else
            echo "versioned=ghcr.io/litjourney/juicity:${{ github.event.inputs.tag }}" >> $GITHUB_OUTPUT
          fi
      - name: Build and release Docker images
        uses: docker/build-push-action@v4
        with:
          platforms: linux/386,linux/amd64,linux/arm64,linux/s390x
          file: jc.Dockerfile
          context: juicity
          tags: |
            ${{ steps.tag.outputs.latest }}
            ${{ steps.tag.outputs.versioned }}
          push: true